version: "2"
services:
  # This service MUST have the name "kdc-kadmin" otherwise every kerberos client won't be able to talk with the KDC.
  # If you would like to change the name edit the file configureKerberosClient.sh and change the configurations
  # "kdc" and "admin_server" in the /etc/krb5.conf section.
  kdc-kadmin:
    build: ./kdc-kadmin
    env_file: kerberos.env
    domainname: pxf.greenplum.internal
    hostname: kdc
    ports:
      - "88:88/tcp"
      - "88:88/udp"
      - "749:749/tcp"
      - "749:749/udp"
      - "750:750/tcp"
      - "750:750/udp"
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
      - /private/var/data/db2_compose/keytabs:/keytabs

  kerberos-client:
    build: ./kerberos-client
    env_file: kerberos.env
    depends_on:
      - kdc-kadmin

  db2:
    env_file: db2.env
    image: ibmcom/db2
    container_name: pxfdb2
    domainname: pxf.greenplum.internal
    hostname: db2
    ports:
      - "50000:50000"
    privileged: true
    volumes:
      - /private/var/data/db2_compose:/database
    depends_on:
      - kdc-kadmin



#  docker run -itd \
#  --name mydb2 \
#  --privileged=true \
#  -p 50000:50000 \
#  -e LICENSE=accept \
#  -e DB2INST1_PASSWORD=choose-your-password \
#  -e DBNAME=testdb \
#  -v /private/var/data/db2:/database \
#  ibmcom/db2


# NOTE:
#  "env_file: kerberos.env" is optional.
#  In case no .env file is supplied, nor any environment variable is set, the following values will be used:
#   REALM=EXAMPLE.COM
#   SUPPORTED_ENCRYPTION_TYPES=aes256-cts-hmac-sha1-96:normal
#   KADMIN_PRINCIPAL=kadmin/admin
#   KADMIN_PASSWORD=MITiys4K5
